config/routes.rb
Glist::Application.routes.draw do
  resources :items, :functions, :lists, :picks
  root :to => "items#index"
end

app/models/function.rb
class Function < ActiveRecord::Base
  has_many :items
  validates_uniqueness_of :name

  scope :order_by_name, -> { order('functions.name ASC') }

  def name
    self[:name].upcase
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :function

  validates_presence_of :name, :weight

  scope :order_by_function_name, -> {
    includes(:function).
    order('functions.name, items.name')
  }

  def function_name_and_name
    "#{function.name.upcase} #{name}"
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessor :list_id

  has_many :picks, -> { includes(:item) }, :dependent => :destroy
  has_many :packed_picks, -> { where(packed: true) }, :class_name => 'Pick'
  has_many :worn_picks, -> { where(packed: false) }, :class_name => 'Pick'

  has_many :items, :through => :picks
  has_many :packed_items, :class_name => 'Item', :through => :packed_picks, :source => :item
  has_many :worn_items, :class_name => 'Item', :through => :worn_picks, :source => :item

  scope :order_by_name, -> { order(:name) }

  before_create :populate_picks, :if => :list_id?

  def list_id?
    !list_id.blank?
  end

  def list
    List.find(list_id)
  end

  def weight
    sum_and_truncate(items)
  end

  def packed_weight
    sum_and_truncate(packed_items)
  end

  def worn_weight
    sum_and_truncate(worn_items)
  end

  private
  def sum_and_truncate(val)
    val.sum('weight').to_short_d
  end

  def populate_picks
    list.picks.each do |p|
      self.picks << Pick.new(p.attributes)
    end
  end
end

app/models/pick.rb
class Pick < ActiveRecord::Base
  belongs_to :list
  belongs_to :item, -> { includes(:function) }

  scope :order_by_item_function_name, -> {
    joins('INNER JOIN items ON items.id = picks.item_id INNER JOIN functions ON functions.id = items.function_id').
    order('functions.name, items.name')
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all
  protect_from_forgery

  def load_new_item
    @item = Item.new
  end

  def load_item
    @item = Item.find(params[:id])
  end

  def load_functions
    @functions = Function.order_by_name
  end
end

app/controllers/functions_controller.rb
class FunctionsController < ApplicationController
  before_filter :load_new_item, :only => [:show]
  before_filter :load_functions, :only => [:index, :show]

  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :load_new_item, :only => [:index, :new]
  before_filter :load_item, :only => [:destroy, :update, :edit]
  before_filter :load_functions, :only => [:index, :new, :edit]
  before_filter :load_items, :only => [:index]

  def index
  end

  def new
  end

  def create
    @item = Item.create(item_params)
    respond_to do |format|
      format.html { redirect_to items_url }
      format.js { load_items }
    end
  end

  def update
    @item.update_attributes(item_params)
    respond_to do |format|
      format.html { redirect_to items_url }
      format.js do
        render js: "window.location = '#{items_url(:function_id => params[:function_id])}';"
      end
    end
  end

  def destroy
    @item.delete
    redirect_to items_url(:function_id => params[:function_id])
  end

  private
  def load_items
    if params[:function_id].blank?
      @items = Item.order_by_function_name
    else
      function = Function.find(params[:function_id])
      @items = function.items.order_by_function_name
    end
  end

  def item_params
    params[:item].permit!
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :load_list, :only => [:show, :edit, :update, :destroy]
  before_filter :load_lists, :only => [:index, :edit]

  def index
    @list = List.new
  end

  def show
    @items = Item.order_by_function_name
    @picks = @list.picks.order_by_item_function_name
    @pick = Pick.new(:list => @list)
  end

  def create
    @list = List.create!(list_params)
    redirect_to lists_url
  end

  def edit
  end

  def update
    @list.update_attributes(list_params)
    redirect_to lists_url
  end

  def destroy
    @list.delete
    redirect_to lists_url
  end

  private
  def load_list
    @list = List.find(params[:id])
  end

  def load_lists
    @lists = List.order_by_name
  end

  def list_params
    params[:list].permit!
  end
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  def create
    @pick = Pick.create!(params.require(:pick).permit!)

    redirect_to_list_url
  end

  def destroy
    @pick = Pick.find(params.require(:id).permit)
    @pick.delete
    redirect_to_list_url
  end

  private
  def redirect_to_list_url
    redirect_to list_url(@pick.list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def item_columns(item)
    [item.function.name, item.name, item.weight].collect do |field|
      content_tag :td, field
    end.join
  end
end

app/views/functions/index.html.erb
<ul class="list">
  <% @functions.each do |function| %>
    <li><%= link_to function.name.upcase, items_url(:function_id => function.id) %></li>
  <% end %>
</ul>

app/views/items/_form.html.erb
<div id="item-form-container">
  <%= form_for item, :remote => true do |f| %>
    <%= hidden_field_tag :function_id, params[:function_id] %>
    <%= f.text_field :name %>
    <%= f.text_field :weight, :class => 'weight' %>
    <%= f.select :function_id, options_from_collection_for_select(functions, 'id', 'name', item.function_id) %>
    <%= f.submit 'Save', :style => 'display:inline' %>
  <% end %>
</div>

app/views/items/_table.html.erb
<% items.each do |item| %>
  <tr>
    <%= raw(item_columns(item)) %>
    <td><%= link_to 'Edit', edit_item_url(item, :function_id => params[:function_id]) %></td>
    <td><%= link_to 'Delete', item_url(item, :function_id => params[:function_id]), :method => :delete %></td>
  </tr>
<% end %>

app/views/items/create.js.erb
$('#content').prepend("<%= escape_javascript(render("shared/error_messages", :target => @item)) %>");
$('#items-table').html("<%= escape_javascript(render("table", :items => @items)) %>");
$('#item-form-container').toggleClass('loading');
stripe();

app/views/items/edit.html.erb
<%= render "form", :item => @item, :functions => @functions %>

app/views/items/index.html.erb
<%= render "form", :item => @item, :functions => @functions %>
<table id="items-table">
  <%= render "table", :items => @items %>
</table>

app/views/items/new.html.erb
<%= render "form", :item => @item, :functions => @functions %>

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html>
  <head>
    <%= stylesheet_link_tag('screen', :media => 'screen') %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <ul class="nav">
      <li><%= link_to 'LISTS', lists_url %></li>
      <li><%= link_to 'ITEMS', items_url %></li>
      <li><%= link_to 'FUNCTIONS', functions_url %></li>
    </ul>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for list do |f| %>
  <p>
    <%= f.text_field :name %>
    <%= f.select :list_id, "<option value=\"\"></option>".html_safe + options_from_collection_for_select(lists, 'id', 'name') %>
    <%= f.submit 'Save' %>
  </p>
<% end %>

app/views/lists/edit.html.erb
<%= render "form", :list => @list, :lists => @lists %>

app/views/lists/index.html.erb
<%= render "form", :list => @list, :lists => @lists %>
<ul class="list">
  <% @lists.each do |list| %>
    <li>
      <%= link_to list.name.upcase, list %>
      <%= link_to 'DELETE', list_url(list), :method => :delete, :style => "float:right; margin-right: 10px" %>
      <%= link_to 'EDIT', edit_list_url(list), :style => "float:right; margin-right: 10px" %>
    </li>
  <% end %>
</ul>

app/views/lists/show.html.erb
<h2><%= @list.name.upcase %></h2>
<%= form_for(@pick) do |f| %>
  <%= f.hidden_field :list_id %>
  <p>
    <%= f.select :item_id, options_from_collection_for_select(@items, 'id', 'function_name_and_name') %>
    <%= f.check_box :packed %>
    <%= f.submit 'Save' %>
  </p>
<% end %>

<table class="list-weights">
  <tr>
    <td>packed<br/><%= @list.packed_weight %> oz<br/><%= @list.packed_weight.to_lbs %> lbs</td>
    <td>worn<br/><%= @list.worn_weight %> oz<br/><%= @list.worn_weight.to_lbs %> lbs</td>
    <td>total<br/><%= @list.weight %> oz<br/><%= @list.weight.to_lbs %> lbs</td>
  </tr>
</table>

<table>
  <% @picks.each do |pick| %>
    <tr>
      <%= raw(item_columns(pick.item)) %>
      <td><%= pick.packed? ? 'packed' : 'worn' %></td>
      <td><%= link_to 'Delete', pick_url(pick), :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/shared/_error_messages.html.erb
<% if target.present? && target.errors.any? %>  
  <div id="item-error">
    <ul>  
    <% target.errors.full_messages.each do |msg| %>  
      <li><%= msg %></li>  
    <% end %>  
    </ul>  
  </div>
<% end %>